In [14]:
# あたらしいPythonによるデータ分析の教科書
# 4.1 NumPy 02P
import numpy as np 


In [15]:
# 一次元配列
np.array([1, 2, 3])

array([1, 2, 3])

In [16]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [17]:
print(a)

[1 2 3]


In [18]:
type(a)

numpy.ndarray

In [19]:
a.shape

(3,)

In [20]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
b.shape

(2, 3)

In [22]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c1

array([0, 1, 2, 3, 4, 5])

In [23]:
c2 = c1.reshape((2, 3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [25]:
c4 = c2.flatten()
c4

array([0, 1, 2, 3, 4, 5])

In [26]:
# a.type

In [27]:
a.dtype

dtype('int64')

In [28]:
d = np.array([1, 2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [29]:
d.dtype

dtype('int16')

In [30]:
a

array([1, 2, 3])

In [31]:
a[0]

1

In [32]:
a[1:]

array([2, 3])

In [33]:
a[-1]

3

In [34]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
b[0]

array([1, 2, 3])

In [36]:
b[1, 0]

4

In [37]:
b[:, 2]

array([3, 6])

In [38]:
b[1, :]

array([4, 5, 6])

In [39]:
b[0, 1:]

array([2, 3])

In [40]:
# 100P
b[:, [0, 2]]

array([[1, 3],
       [4, 6]])

In [41]:
a

array([1, 2, 3])

In [42]:
a[2] = 4

In [43]:
a

array([1, 2, 4])

In [44]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
b[1, 2] = 7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [46]:
b[:, 2] = 8
b

array([[1, 2, 8],
       [4, 5, 8]])

In [47]:
# 参照とコピー
a1 = a
a1

array([1, 2, 4])

In [48]:
a1[1] = 5
a1

array([1, 5, 4])

In [49]:
a

array([1, 5, 4])

In [50]:
a2 = a.copy()
a2

array([1, 5, 4])

In [51]:
a2[0] = 6
a2

array([6, 5, 4])

In [52]:
a

array([1, 5, 4])

In [53]:
c2


array([[0, 1, 2],
       [3, 4, 5]])

In [54]:
c3 = c2.ravel()
c4 = c2.flatten()
c3[0] = 6
c4[1] = 7

In [55]:
c3

array([6, 1, 2, 3, 4, 5])

In [56]:
c4

array([0, 7, 2, 3, 4, 5])

In [57]:
c2

array([[6, 1, 2],
       [3, 4, 5]])

In [58]:
c4

array([0, 7, 2, 3, 4, 5])

In [59]:
py_list1 = [0, 1]
py_list2 = py_list1[:]
py_list2[0] = 2
print(py_list1)
print(py_list2)

[0, 1]
[2, 1]


In [60]:
np_array1 = np.array([0, 1])
np_array2 = np_array1[:]
np_array2[0] = 2
print(np_array1)
print(np_array2)

[2 1]
[2 1]


In [61]:
np_array1


array([2, 1])

In [62]:
np_array2

array([2, 1])

In [63]:
# 数列を返す
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [66]:
# 乱数
rng = np.random.default_rng()
f = rng.random((3, 2))

In [67]:
f

array([[0.93012081, 0.12412544],
       [0.60885142, 0.1616206 ],
       [0.18745839, 0.43332378]])

In [68]:
rng = np.random.default_rng(123)
f = rng.random((3, 2))
f

array([[0.68235186, 0.05382102],
       [0.22035987, 0.18437181],
       [0.1759059 , 0.81209451]])

In [71]:
rng = np.random.default_rng(123)
rng.integers(1, 10)

1

In [72]:
rng = np.random.default_rng(123)
rng.integers(1, 10, size=(3, 3))

array([[1, 7, 6],
       [1, 9, 2],
       [3, 2, 4]])

In [73]:
rng = np.random.default_rng(123)
rng.uniform(0.0, 5.0, size=(2, 3))

array([[3.41175932, 0.26910509, 1.10179936],
       [0.92185905, 0.87952951, 4.06047253]])

In [75]:
rng = np.random.default_rng(123)
rng.uniform(size=(4, 3))

array([[0.68235186, 0.05382102, 0.22035987],
       [0.18437181, 0.1759059 , 0.81209451],
       [0.923345  , 0.2765744 , 0.81975456],
       [0.88989269, 0.51297046, 0.2449646 ]])

In [76]:
rng = np.random.default_rng(123)
rng.standard_normal(size=(4, 2))

array([[-0.98912135, -0.36778665],
       [ 1.28792526,  0.19397442],
       [ 0.9202309 ,  0.57710379],
       [-0.63646365,  0.54195222]])

In [78]:
rng = np.random.default_rng(123)
rng.normal(50, 10, 3)

array([40.1087865 , 46.32213349, 62.87925261])

In [79]:
# 同じ要素の数列を作る
np.zeros(3)

array([0., 0., 0.])

In [80]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [81]:
np.ones(2)

array([1., 1.])

In [84]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [85]:
# 単位行列
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [86]:
np.full(3, 3.14)

array([3.14, 3.14, 3.14])

In [87]:
np.full((2, 4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [88]:
np.nan

nan

In [89]:
np.array([1, 2, np.nan])

array([ 1.,  2., nan])

In [90]:
# 範囲指定で均等割りデータを作る
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [91]:
np.arange(0.0, 1.1, 0.25)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [92]:
np.linspace(0, np.pi, 21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

In [94]:
# 要素間の差分
l = np.array([2, 2, 6, 1, 3])
np.diff(l)

array([ 0,  4, -5,  2])

In [96]:
# 連結
print(a)
print(a1)

[1 5 4]
[1 5 4]


In [97]:
np.concatenate([a, a1])

array([1, 5, 4, 1, 5, 4])

In [98]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [100]:
b1 = np.array([[10], [20]])
b1

array([[10],
       [20]])

In [101]:
np.concatenate([b, b1], axis=1)

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [103]:
np.hstack([b, b1])

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [104]:
b2 = np.array([30, 60, 45])
b2

array([30, 60, 45])

In [105]:
b3 = np.vstack([b, b2])
b3

array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

In [106]:
# 分割
first, second = np.hsplit(b3, [2])

In [107]:
first

array([[ 1,  2],
       [ 4,  5],
       [30, 60]])

In [108]:
second

array([[ 8],
       [ 8],
       [45]])

In [109]:
first, second = np.vsplit(b3, [2])

In [110]:
first

array([[1, 2, 8],
       [4, 5, 8]])

In [111]:
second

array([[30, 60, 45]])

In [112]:
# 配置
b

array([[1, 2, 8],
       [4, 5, 8]])

In [113]:
b.T

array([[1, 4],
       [2, 5],
       [8, 8]])