In [28]:
# あたらしいPythonによるデータ分析の教科書
# 4.1 NumPy 02P
import numpy as np 


In [29]:
# 一次元配列
np.array([1, 2, 3])

array([1, 2, 3])

In [30]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [31]:
print(a)

[1 2 3]


In [32]:
type(a)

numpy.ndarray

In [33]:
a.shape

(3,)

In [34]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
b.shape

(2, 3)

In [36]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c1

array([0, 1, 2, 3, 4, 5])

In [37]:
c2 = c1.reshape((2, 3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [38]:
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [39]:
c4 = c2.flatten()
c4

array([0, 1, 2, 3, 4, 5])

In [40]:
a.type

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [ ]:
a.dtype

dtype('int64')

In [ ]:
d = np.array([1, 2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [ ]:
d.dtype

dtype('int16')

In [ ]:
a

array([1, 2, 3])

In [ ]:
a[0]

1

In [ ]:
a[1:]

array([2, 3])

In [ ]:
a[-1]

3

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b[0]

array([1, 2, 3])

In [ ]:
b[1, 0]

4

In [ ]:
b[:, 2]

array([3, 6])

In [ ]:
b[1, :]

array([4, 5, 6])

In [ ]:
b[0, 1:]

array([2, 3])

In [ ]:
# 100P
b[:, [0, 2]]

array([[1, 3],
       [4, 6]])

In [ ]:
a

array([1, 2, 3])

In [ ]:
a[2] = 4

In [ ]:
a

array([1, 2, 4])

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b[1, 2] = 7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [ ]:
b[:, 2] = 8
b

array([[1, 2, 8],
       [4, 5, 8]])

In [ ]:
# 参照とコピー
a1 = a
a1

array([1, 2, 4])

In [ ]:
a1[1] = 5
a1

array([1, 5, 4])

In [ ]:
a

array([1, 5, 4])

In [ ]:
a2 = a.copy()
a2

array([1, 5, 4])

In [ ]:
a2[0] = 6
a2

array([6, 5, 4])

In [ ]:
a

array([1, 5, 4])

In [ ]:
c2


array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
c3 = c2.ravel()
c4 = c2.flatten()
c3[0] = 6
c4[1] = 7

In [ ]:
c3

array([6, 1, 2, 3, 4, 5])

In [ ]:
c4

array([0, 7, 2, 3, 4, 5])

In [ ]:
c2

array([[6, 1, 2],
       [3, 4, 5]])

In [ ]:
c4

array([0, 7, 2, 3, 4, 5])

In [ ]:
py_list1 = [0, 1]
py_list2 = py_list1[:]
py_list2[0] = 2
print(py_list1)
print(py_list2)

[0, 1]
[2, 1]


In [ ]:
np_array1 = np.array([0, 1])
np_array2 = np_array1[:]
np_array2[0] = 2
print(np_array1)
print(np_array2)

[2 1]
[2 1]


In [ ]:
np_array1


array([2, 1])

In [ ]:
np_array2

array([2, 1])

In [ ]:
# 数列を返す
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [ ]:
# 乱数
rng = np.random.default_rng()
f = rng.random((3, 2))

NameError: name 'np' is not defined